version: "3.3"
services:
  postgresql:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: "aso"
      POSTGRES_PASSWORD: "aso"
      POSTGRES_DB: "aso"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:

    